ALEJA                   AL
ALEJA                   AL.
ALLEY                   AL
ALLEY                   AL.
ALLEY                   ALL
ALLEY                   ALL.
ALLEY                   ALY
ALLEY                   ALY.
ARCADE                  ARC
ARCADE                  ARC.
AVENUE                  AV
AVENUE                  AV.
AVENUE                  AVDA
AVENUE                  AVDA.
AVENUE                  AVE
AVENUE                  AVE.
AVENUE                  AVEN
AVENUE                  AVEN.
AVENUE                  AVENIDA
AVENUE                  AVENIDA.
AVENUE DES              AV DES
AVENUE DES              AV DES.
BASSIN                  BAS
BASSIN                  BAS.
BASSINS                 BAS
BASSINS                 BAS.
BEACH                   BCH
BEACH                   BCH.
BEND                    BND
BEND                    BND.
BERGE                   BER
BERGE                   BER.
BLUFFS                  BLFS
BLUFFS                  BLFS.
BOUCLE                  BCLE
BOUCLE                  BCLE.
BOULEVARD               BD
BOULEVARD               BD.
BOULEVARD               BL
BOULEVARD               BL.
BOULEVARD               BV
BOULEVARD               BV.
BOULEVARD               BLV
BOULEVARD               BLV.
BOULEVARD               BVD
BOULEVARD               BVD.
BOULEVARD               BLVD
BOULEVARD               BLVD.
BOULEVARD               BOUL
BOULEVARD               BOUL.
BOULEVARD               BLVED
BOULEVARD               BLVED.
BULWAR                  BULW
BULWAR                  BULW.
BRIDGE                  BRDG
BRIDGE                  BRDG.
BRIDGE                  BRG
BRIDGE                  BRG.
BROOK                   BRK
BROOK                   BRK.
BROOKS                  BRKS
BROOKS                  BRKS.
BUNDESSTRASSE           BUNDESSTR
BUNDESSTRASSE           BUNDESSTR.
BUTTE                   BUT
BUTTE                   BUT.
BYPASS                  BYP
BYPASS                  BYP.
CANYON                  CYN
CANYON                  CYN.
CALE                    CAL
CALE                    CAL.
CAPE                    CPE
CAPE                    CPE.
CARREFOUR               CAR
CARREFOUR               CAR.
CARRIERE                CARE
CARRIERE                CARE.
CAUSEWAY                CAUSE
CAUSEWAY                CAUSE.
CAUSEWAY                CSWY
CAUSEWAY                CSWY.
CAVEE                   CAV
CAVEE                   CAV.
CENTER                  CNTR
CENTER                  CNTR.
CENTER                  CTR
CENTER                  CTR.
CHATEAU                 CHA
CHATEAU                 CHA.
CHEMIN                  CH
CHEMIN                  CH.
CHEMIN                  CHE
CHEMIN                  CHE.
CHEMINEMENT             CHEM
CHEMINEMENT             CHEM.
CIRCLE                  CIR
CIRCLE                  CIR.
CIRCLE                  CIRC
CIRCLE                  CIRC.
CIRCLES                 CIRS
CIRCLES                 CIRS.
CLIFFS                  CLFS
CLIFFS                  CLFS.
CITE                    CIT
CITE                    CIT.
CLOS                    CL
CLOS                    CL.
CLOSE                   CL
CLOSE                   CL.
COLONEL                 COL
COLONEL                 COL.
COMMON                  CMN
COMMON                  CMN.
COMMON                  CMNS
COMMON                  CMNS.
COMMON                  COMMONS
COMMON                  COMMONS.
COMMONS                 CMN
COMMONS                 CMN.
COMMONS                 CMNS
COMMONS                 CMNS.
CORNER                  COR
CORNER                  COR.
CORNERS                 CORS
CORNERS                 CORS.
CONTOUR                 CTR
CORNICHE                CORN
COTE                    COT
COUR                    C
COUR                    CR
COURS                   CRS
COURT                   CRT
COURT                   CRT.
COURT                   CT
COURT                   CT.
COURTS                  CTS
COURTS                  CTS.
COVE                    CV
COVE                    CV.
COVES                   CVS
COVES                   CVS.
CREEK                   CR
CREEK                   CRK
CREEK                   CRK.
CRESCENT                CRES
CRESCENT                CRES.
CRESCENT                CRESC
CRESCENT                CRESC.
CRESCENT                CRESNT
CREST                   CRST
CREST                   CRST.
CROSSING                CRSG
CROSSING                CRSG.
CROSSING                XING
CROSSING                XING.
CROSSROADS              XRDS
CROSSROADS              XRDS.
DESCENTE                DESC
DRIVE                   DR
DRIVE                   DR.
DRIVE                   DRV
DRIVE                   DRV.
DRIVES                  DRS
DRIVES                  DRS.
ENCLAVE                 ENC
ENCLOS                  ENC
ESPACE                  ESP
ESPLANADE               ESP
ESTATE                  EST
ESTATE                  EST.
ESTATES                 ESTS
ESTATES                 ESTS.
EXPRESSWAY              EXPR
EXPRESSWAY              EXPR.
EXPRESSWAY              EXPY
EXPRESSWAY              EXPY.
EXPRESSWAY              EXWY
EXPRESSWAY              EXPSWY
EXPRESSWAY              EXWY.
EXPRESSWAY              EXPWY
EXPRESSWAY              EXPWY.
EXTENSION               EXT
EXTENSION               EXT.
EXTENSIONS              EXTS
EXTENSIONS              EXTS.
FALLS                   FLS
FALLS                   FLS.
FARM-TO-MARKET          F-M
FARM-TO-MARKET          FM
FARM-TO-MARKET          FM.
FAUBOURG                FAUB
FAUBOURG                FAUB.
FIELD                   FLD
FIELD                   FLD.
FIELDS                  FLDS
FIELDS                  FLDS.
FLATS                   FLTS
FLATS                   FLTS.
FOREST                  FRST
FOREST                  FRST.
FORKS                   FRKS
FORKS                   FRKS.
FORUM                   FORM
FREEWAY                 FRWY
FREEWAY                 FRWY.
FREEWAY                 FWY
FREEWAY                 FWY.
GLEN                    GLN
GLEN                    GLN.
GRAND BOULEVARD         GBD
GRAND BOULEVARD         GBLVD
GREEN                   GRN
GREEN                   GRN.
GREEN                   GRNS
GREEN                   GRNS.
GREENS                  GRN
GREENS                  GRN.
GREENS                  GRNS
GREENS                  GRNS.
GROVE                   GRV
GROVE                   GRV.
GROVES                  GRVS
GROVES                  GRVS.
GRANDE RUE              GR
GRIMPETTE               GRP
GRIMPETTE               GRP.
HARBOR                  HBR
HAVEN                   HVN
HAVEN                   HVN.
HEIGHTS                 HTS
HIGHWAY                 HWY
HIGHWAY                 HWY.
HIGHWAY                 HY
HIGHWAY                 HY.
HIGHWAY                 HIWAY
HIGHWAY                 HIWAY.
HIGHWAY                 HIGWAY
HIGHWAY                 HIGWAY.
HIGHWAY                 NHWY
HIGHWAY                 NHWY.
HIGHWAY                 HIHGWAY
HIGHWAY                 HIHGWAY.
HILL                    HL
HILLS                   HLS
HILLS                   HLS.
HOLLOW                  HOLW
HOLLOW                  HOLW.
IMMEUBLE                IMM
IMMEUBLE                IMM.
IMPASSE                 IMP
IMPASSE                 IMP.
ISLAND                  IS
ISLAND                  IS.
JARDIN                  J
JUNCTION                JCT
JUNCTION                JCT.
KEY                     KY
KEY                     KY.
KEYS                    KYS
KEYS                    KYS.
KNOLL                   KNL
KNOLL                   KNL.
KNOLLS                  KNLS
KNOLLS                  KNLS.
LAKES                   LKS
LAKES                   LKS.
LAND                    LAND
LAND                    LAND.
LANDESSTRASSE           LANDESSTR
LANDESSTRASSE           LANDESSTR.
LANDING                 LNDG
LANDING                 LNDG.
LANDSTRASSE             LANDSTR
LANDSTRASSE             LANDSTR.
LANE                    LA
LANE                    LA.
LANE                    LN
LANE                    LN.
LEVEE                   LEV
LIEU DIT                L-D
LIEU DIT                LD
LIEU DIT                LIEU
LIEU-DIT                L-D
LIEU-DIT                LD
LIEU-DIT                LIEU
LIGHTS                  LGTS
LIGHTS                  LGTS.
LOCKS                   LCKS
LOCKS                   LCKS.
LOOP                    LP
LOOP                    LP.
LOTISSEMENT             LOT
LOTISSEMENT             LOT.
MALL                    ML
MALL                    ML.
MANOR                   MNR
MANOR                   MNR.
MANORS                  MNRS
MANORS                  MNRS.
MEADOW                  MDW
MEADOW                  MDW.
MEADOWS                 MDWS
MEADOWS                 MDWS.
MILLS                   MLS
MILLS                   MLS.
MOTORWAY                MRWY
MOTORWAY                MRWY.
MOTORWAY                MTRWY
MOTORWAY                MTRWY.
MOTORWAY                MTWY
MOTORWAY                MTWY.
MOUNT                   MT
MOUNT                   MT.
OSIEDLE                 OS
OSIEDLE                 OS.
OVERPASS                OPAS
OVERPASS                OPAS.
OVERPASS                OVER
OVERPASS                OVER.
OVERPASS                OVPS
OVERPASS                OVPS.
OVERPASS                OVRPS
OVERPASS                OVRPS.
PARK                    PK
PARK                    PK.
PARK                    PRK
PARK                    PRK.
PARKWAY                 PKY
PARKWAY                 PKY.
PARKWAY                 PKW
PARKWAY                 PKW.
PARKWAY                 PKWY
PARKWAY                 PKWY.
PARKWAY                 PKWAY
PARKWAY                 PKWAY.
PARKWAY                 PRKWY
PARKWAY                 PRKWY.
PARVIS                  PAR
PASEO                   PSO
PASS                    PS
PASS                    PS.
PASSAGE                 PASS
PASSAGE                 PASS.
PASSAGE                 PSGE
PASSAGE                 PSGE.
PATH                    PTH
PATH                    PTH.
PETITE AVENUE           PTA
PETITE IMPASSE          PTI
PETITE ROUTE            PRT
PETITE RUE              PTR
PIKE                    PKE
PIKE                    PKE.
PINE                    PNE
PINE                    PNE.
PINES                   PNES
PINES                   PNES.
PLAC                    PL
PLAC                    PL.
PLACE                   PL
PLACE                   PL.
PLACE                   PLA
PLACE                   PLA.
PLACE                   PLAC
PLACE                   PLAC.
PLACE                   PLC
PLACE                   PLC.
PLAINS                  PLNS
PLAINS                  PLNS.
PLAZA                   PLZ
PLAZA                   PLZ.
POINT                   PNT
POINT                   PNT.
POINT                   PT
POINT                   PT.
POINTS                  PTS
POINTS                  PTS.
PORTE                   PTE
POURTOUR                POUR
POURTOUR                POUR.
PRAIRIE                 PR
PRAIRIE                 PR.
PROMENADE               PROM
QUAI                    Q
QUAI                    Q.
QUARTIER                QUA
RACCOURCI               RAC
RACCOURCI               RAC.
RADIAL                  RADL
RADIAL                  RADL.
RAMP                    RMP
RAMP                    RMP.
RAMPE                   RPE
RAPIDS                  RPDS
RAPIDS                  RPDS.
REMPART                 REM
RESIDENCE               RES
RESIDENCE               RES.
REST                    RST
REST                    RST.
RIDGE                   RDG
RIDGE                   RDG.
RIDGES                  RDGS
RIDGES                  RDGS.
ROAD                    RD
ROAD                    RD.
ROADS                   RDS
ROADS                   RDS.
ROCADE                  ROC
ROCADE                  ROC.
ROND POINT              ROND
ROND POINT              RP
ROND POINT              RP.
ROND-POINT              ROND
ROND-POINT              RP
ROND-POINT              RP.
ROTONDE                 ROT
ROTONDE                 RTD
ROUTE                   RTE
RUE                     R
RUE                     R.
RUE DE                  RUE
SENTIER                 SENT
SENTIER                 SENT.
SHOALS                  SHLS
SHOALS                  SHLS.
SHORES                  SHRS
SHORES                  SHRS.
SKYWAY                  SKWY
SKYWAY                  SKWY.
SPRINGS                 SPGS
SPRINGS                 SPGS.
SQUARE                  SQ
SQUARE                  SQ.
SQUARE                  SQR
SQUARE                  SQR.
SQUARES                 SQS
SQUARES                 SQS.
STRASSE                 STR
STRASSE                 STR.
STRAVENUE               STRA
STRAVENUE               STRA.
STREET                  ST
STREET                  ST.
STREET                  STEET
STREET                  STR
STREET                  STR.
STREET                  STREETS
STREET                  STS
STREET                  STS.
STREETS                 STS
STREETS                 STS.
TERRACE                 TER
TERRACE                 TER.
TERRACE                 TERR
TERRACE                 TERR.
TERRACE                 TRC
TERRACE                 TRC.
TERRASSE                TER
TERTRE                  TRT
THROUGHWAY              THRUWAY
THROUGHWAY              THWY
THROUGHWAY              THWY.
TOUR                    TR
TOUR                    TR.
TRACE                   TRCE
TRACE                   TRCE.
TRACK                   TRAK
TRACK                   TRAK.
TRAFFICWAY              TFCWY
TRAFFICWAY              TFCWY.
TRAFFICWAY              TFWY
TRAFFICWAY              TFWY.
TRAFFICWAY              TRFY
TRAFFICWAY              TRFY.
TRAFFICWAY              TRWY
TRAFFICWAY              TRWY.
TRAIL                   TR
TRAIL                   TR.
TRAIL                   TRL
TRAIL                   TRL.
TRAILER                 TRLR
TRAILER                 TRLR.
TRAVERSE                TRA
TUNNEL                  TUN
TUNNEL                  TUN.
TUNNEL                  TUNL
TUNNEL                  TUNL.
TUNNEL                  TUNN
TUNNEL                  TUNN.
TURNPIKE                TPK
TURNPIKE                TPK.
TURNPIKE                TPKE
TURNPIKE                TPKE.
ULICA                   UL
ULICA                   UL.
UNDERPASS               UNP
UNDERPASS               UNP.
UNDERPASS               UNPS
UNDERPASS               UNPS.
UNDERPASS               UNRPS
UNDERPASS               UNRPS.
UNDERPASS               UPAS
UNDERPASS               UPAS.
VENELLE                 VEN
VIEILLE ROUTE           VRTE
VIEUX CHEMIN            VCHE
VIEW                    VW
VIEW                    VW.
VIEWS                   VWS
VIEWS                   VWS.
VILLAGE                 VGE
VILLAGE                 VLG
VILLAGE                 VLG.
VILLAGES                VLGS
VILLAGES                VLGS.
VISTA                   VIS
VISTA                   VIS.
VOIE                    V
WAY                     WY
WAY                     WY.
WAYS                    WAYS
WAYS                    WAYS.
WELLS                   WLS
WELLS                   WLS.
WYBRZEZE                WYB
WYBRZEZE                WYB.
ZONE ARTISANALE         ZA
ZONE D'ACTIVITE         Z.A.
ZONE D'ACTIVITE         ZA.
ZONE INDUSTRIELLE       Z.I
ZONE INDUSTRIELLE       Z.I.
ZONE INDUSTRIELLE       ZI
